/* Generated by lastchange.py, do not edit.*/

#ifndef GPU_CONFIG_GPU_LISTS_VERSION_H_
#define GPU_CONFIG_GPU_LISTS_VERSION_H_

#define GPU_LISTS_VERSION "1bcb622eb21b876b3a27352fece49e1d58cebfd1"

#endif  // GPU_CONFIG_GPU_LISTS_VERSION_H_
